In [1]:
# load modules
import geopandas as gpd
import pandas as pd
import fiona
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'notebook'

import matplotlib.pyplot as plt

In [2]:
# load the file with the narratives from the crash report

narratives1 = pd.read_csv("Data/Franklin_DocumentNumber_Narrative_part1.csv")
narratives2 = pd.read_csv("Data/Franklin_DocumentNumber_Narrative_part2.csv")

In [ ]:
# merge the files in one
narratives = pd.concat([narratives1, narratives2], ignore_index=True)

In [ ]:
# save the narratives as its own csv
narratives.to_csv("Data/Franklin_DocumentNumber_Narrative_full.csv", index=False)

In [24]:
narratives

,DocumentNumber,County,Narrative
0,20202168971,Franklin County,Unit# 1 a pedestrian was crossing US-40 from s...
1,20202168999,Franklin County,Unit 1 was westbound on SR 317 towards Parsons...
2,20202172825,Franklin County,Unit 2 was traveling south on SR 104 south of ...
3,20202183697,Franklin County,Unit 1 was crossing US 40 outside of the cross...
4,20202206898,Franklin County,Unit 1 was driving south on SR 3 just north of...
...,...,...,...
115676,20258172808,Franklin County,On Sunday; September 21; 2025; Unit 2 was stop...
115677,20258173076,Franklin County,On above date and time U-1 failed to yield at ...
115678,20258173087,Franklin County,Unit #1 was traveling eastbound on Josephus Ln...
115679,20258173091,Franklin County,During the night of September 13th; 2025 after...
115680,20258173093,Franklin County,Unit #1 was northbound on Santa Maria Lane whe...

In [5]:
# now search for the top 10 (or top 20) fast food chains in the narratives

# load the fastfood places
fastfood = gpd.read_file("Data/fastfood_all_ohio.gpkg", layer="fastfood")

# check the occurances of the pizza chains
fastfood_counts = fastfood["name"].value_counts()

# convert to a DataFrame for nicer display
fastfood_counts_df = fastfood_counts.reset_index()

print(fastfood_counts[:10])
top10_fastfood = fastfood_counts[:10]
top20_fastfood = fastfood_counts[:20]


# load the pizza places
pizza = gpd.read_file("Data/pizza_places_ohio.gpkg", layer="pizza_places")
# check the occurances of the pizza chains
pizza_counts = pizza["name"].value_counts()

# convert to dataframe for nicer display
pizza_counts_df = pizza_counts.reset_index()
#pizza_counts_df.columns = ["fastfood_chain", "count"]

print(pizza_counts[:10])
top10_pizza = pizza_counts[:10]
top20_pizza = pizza_counts[:20]

name
McDonald's     614
Subway         585
Wendy's        368
Taco Bell      325
Burger King    281
Arby's         245
Chipotle       214
Domino's       162
Dunkin'        162
KFC            156
Name: count, dtype: int64
name
Pizza Hut                174
Domino's                 161
Little Caesars            99
Papa John's               83
Marco's Pizza             83
Donatos Pizza             69
LaRosa's Pizzeria         30
Jet's Pizza               19
Gionino's Pizzeria        18
East of Chicago Pizza     18
Name: count, dtype: int64

In [6]:
pizza_10names = top10_pizza.index[:]
fastfood_10names = top10_fastfood.index[:]

print(pizza_10names)
print(fastfood_10names)

Index(['Pizza Hut', 'Domino's', 'Little Caesars', 'Papa John's',
       'Marco's Pizza', 'Donatos Pizza', 'LaRosa's Pizzeria', 'Jet's Pizza',
       'Gionino's Pizzeria', 'East of Chicago Pizza'],
      dtype='object', name='name')
Index(['McDonald's', 'Subway', 'Wendy's', 'Taco Bell', 'Burger King', 'Arby's',
       'Chipotle', 'Domino's', 'Dunkin'', 'KFC'],
      dtype='object', name='name')

In [7]:
# the spelling of the restaurant places can vary in the reports, so I will look for apostrophes in the name and 
# just go with the name before the apostrophe
# (the order matters)
pizza_names_stub = [name.split("s ")[0] for name in top10_pizza.index[:]]
pizza_names_stub = [name.split("'")[0] for name in top10_pizza.index[:]]
print(pizza_names_stub)

['Pizza Hut', 'Domino', 'Little Caesars', 'Papa John', 'Marco', 'Donatos Pizza', 'LaRosa', 'Jet', 'Gionino', 'East of Chicago Pizza']

In [8]:
# the spelling of the restaurant places can vary in the reports, so I will look for apostrophes in the name and 
# just go with the name before the apostrophe
# (the order matters)

# same for the fastfood places
fastfood_names_stub = [name.split("'")[0] for name in top10_fastfood.index[:]]
print(fastfood_names_stub)

['McDonald', 'Subway', 'Wendy', 'Taco Bell', 'Burger King', 'Arby', 'Chipotle', 'Domino', 'Dunkin', 'KFC']

In [9]:
# now we have the list of the top 10 restaurant names,
# now look through the narratives and search for these words
# issue might be that there is different writing of the restaurants in the narrative
# like Dominos instead of Domino's

# set up a new dictionary to store the information
narrative_names = {}

for word in fastfood_names_stub:
    if word.strip() == "Arby":
        mask = narratives['Narrative'].str.contains(r'\sArby', case=False, na=False)
    else:
        mask = narratives['Narrative'].str.contains(word, case=False, na=False)
    print(word)
    matching_reports = narratives.loc[mask, 'DocumentNumber']
    narrative_names[word] = matching_reports

McDonald
Subway
Wendy
Taco Bell
Burger King
Arby
Chipotle
Domino
Dunkin
KFC

In [10]:
# check all the DocumentNumbers for a certain fast food chain
print(narrative_names["McDonald"])

497       20203168201
570       20203169023
714       20203171089
986       20203175958
1513      20203183836
             ...
113202    20253155992
113591    20253160667
113951    20253164925
114296    20253168048
115618    20258158560
Name: DocumentNumber, Length: 313, dtype: int64

In [11]:
# just a check to see how often a certain chain is mentioned
key_lengths = {key: len(narrative_names[key]) for key in narrative_names}

print(key_lengths)

{'McDonald': 313, 'Subway': 21, 'Wendy': 90, 'Taco Bell': 49, 'Burger King': 22, 'Arby': 8, 'Chipotle': 22, 'Domino': 6, 'Dunkin': 9, 'KFC': 23}

In [12]:
print(len(narrative_names["McDonald"]))
print(narrative_names["McDonald"])
sorted_narrative_names = sorted(narrative_names, key=lambda k: len(narrative_names[k]), reverse=True)
print(sorted_narrative_names)

313
497       20203168201
570       20203169023
714       20203171089
986       20203175958
1513      20203183836
             ...
113202    20253155992
113591    20253160667
113951    20253164925
114296    20253168048
115618    20258158560
Name: DocumentNumber, Length: 313, dtype: int64
['McDonald', 'Wendy', 'Taco Bell', 'KFC', 'Burger King', 'Chipotle', 'Subway', 'Dunkin', 'Arby', 'Domino']

In [13]:
# just a nicer display
for key in sorted_narrative_names:
    value = narrative_names[key]
    print(f"{key}: {len(value)} mentions")

McDonald: 313 mentions
Wendy: 90 mentions
Taco Bell: 49 mentions
KFC: 23 mentions
Burger King: 22 mentions
Chipotle: 22 mentions
Subway: 21 mentions
Dunkin: 9 mentions
Arby: 8 mentions
Domino: 6 mentions

In [14]:
print(narrative_names["McDonald"])

497       20203168201
570       20203169023
714       20203171089
986       20203175958
1513      20203183836
             ...
113202    20253155992
113591    20253160667
113951    20253164925
114296    20253168048
115618    20258158560
Name: DocumentNumber, Length: 313, dtype: int64

In [15]:
print(narrative_names["Arby"])

29429     20223005258
30842     20223026315
34391     20223079568
87655     20243140054
96775     20243245802
99196     20248243505
104756    20253058957
106800    20253082041
Name: DocumentNumber, dtype: int64

We need to identify now if the mention of McDonald's has anything to do with the crash or is just a location marker

So print the narrative.

In [16]:
# convert dict to df:
narrative_names_df = pd.DataFrame(narrative_names)
print(narrative_names_df)


#narrative_names["McDonald\'s"][]

            McDonald  Subway  Wendy  Taco Bell   Burger King  Arby  Chipotle  \
497     2.020317e+10     NaN    NaN        NaN           NaN   NaN       NaN
570     2.020317e+10     NaN    NaN        NaN           NaN   NaN       NaN
714     2.020317e+10     NaN    NaN        NaN           NaN   NaN       NaN
986     2.020318e+10     NaN    NaN        NaN           NaN   NaN       NaN
1513    2.020318e+10     NaN    NaN        NaN           NaN   NaN       NaN
...              ...     ...    ...        ...           ...   ...       ...
113951  2.025316e+10     NaN    NaN        NaN           NaN   NaN       NaN
114296  2.025317e+10     NaN    NaN        NaN           NaN   NaN       NaN
115281           NaN     NaN    NaN        NaN  2.025805e+10   NaN       NaN
115292           NaN     NaN    NaN        NaN           NaN   NaN       NaN
115618  2.025816e+10     NaN    NaN        NaN           NaN   NaN       NaN

              Domino  Dunkin  KFC
497              NaN     NaN  NaN
570              NaN     NaN  NaN
714              NaN     NaN  NaN
986              NaN     NaN  NaN
1513             NaN     NaN  NaN
...              ...     ...  ...
113951           NaN     NaN  NaN
114296           NaN     NaN  NaN
115281           NaN     NaN  NaN
115292  2.025805e+10     NaN  NaN
115618           NaN     NaN  NaN

[557 rows x 10 columns]

From this I learn that there are in total 557 mentions of the top 10 fastfood chains. After correcting that "nearby" conatins the word "Arby", the list seems to make sense.

In [17]:
# print a random narrative for checking:

print(narrative_names["McDonald"])
mcd_document_numbers = narrative_names["McDonald"]

497       20203168201
570       20203169023
714       20203171089
986       20203175958
1513      20203183836
             ...
113202    20253155992
113591    20253160667
113951    20253164925
114296    20253168048
115618    20258158560
Name: DocumentNumber, Length: 313, dtype: int64

In [18]:
# I want to merge all fastfood documentnumbers in one file, because we don't care which chain it is
fastfood_document_numbers = [number for sublist in narrative_names.values() for number in sublist]
print(fastfood_document_numbers)
print("")
print(len(fastfood_document_numbers))

[20203168201, 20203169023, 20203171089, 20203175958, 20203183836, 20203187027, 20203203074, 20203205393, 20203206891, 20203209872, 20203213688, 20203219266, 20203220156, 20203223118, 20203223786, 20203230214, 20213003067, 20213007603, 20213008111, 20213019000, 20213032957, 20213036003, 20213036618, 20213042366, 20213064942, 20213076893, 20213079954, 20213083612, 20213086224, 20213092935, 20213098667, 20213100942, 20213110226, 20213110998, 20213113543, 20213124404, 20213126391, 20213126401, 20213131830, 20213133761, 20213133929, 20213137368, 20213137369, 20213138405, 20213147182, 20213147903, 20213158332, 20213167027, 20213167993, 20213172526, 20213172991, 20213178281, 20213181554, 20213184797, 20213196046, 20213202678, 20213211246, 20213218825, 20213236606, 20213247289, 20213252304, 20214153745, 20214172355, 20223009625, 20223017802, 20223018939, 20223024456, 20223030614, 20223035880, 20223041337, 20223044905, 20223048055, 20223054870, 20223057259, 20223059341, 20223072085, 20223073333, 20223074471, 20223082708, 20223083163, 20223090187, 20223102193, 20223105239, 20223107749, 20223107750, 20223120979, 20223121375, 20223130182, 20223136365, 20223140065, 20223143431, 20223153391, 20223153711, 20223153715, 20223155155, 20223155190, 20223161758, 20223167545, 20223173187, 20223175974, 20223182763, 20223184586, 20223185418, 20223195201, 20223215227, 20223225353, 20223240492, 20223244051, 20223247092, 20223256287, 20223256288, 20223259677, 20223260191, 20223266578, 20224044513, 20224188018, 20226224960, 20232202973, 20232243727, 20233003792, 20233012691, 20233016331, 20233017120, 20233029086, 20233029359, 20233039454, 20233040680, 20233041052, 20233044275, 20233061073, 20233064269, 20233064270, 20233064273, 20233084577, 20233084982, 20233090374, 20233091926, 20233094924, 20233113600, 20233114175, 20233116226, 20233117278, 20233127527, 20233129547, 20233134101, 20233135339, 20233137921, 20233146462, 20233146809, 20233147315, 20233150182, 20233151422, 20233160140, 20233160221, 20233160529, 20233164613, 20233165560, 20233178725, 20233180369, 20233182059, 20233195867, 20233199815, 20233200097, 20233202874, 20233206327, 20233208869, 20233217303, 20233220875, 20233222933, 20233224054, 20233224873, 20233225853, 20233232864, 20233241464, 20233251422, 20233253826, 20234047655, 20234094391, 20234182468, 20235217247, 20238136823, 20238147181, 20238209140, 20242037665, 20242095732, 20242249165, 20243001623, 20243010361, 20243010363, 20243010364, 20243017006, 20243017034, 20243019734, 20243019845, 20243026063, 20243034431, 20243039435, 20243041406, 20243043232, 20243044223, 20243048014, 20243048196, 20243052165, 20243057134, 20243061504, 20243081666, 20243084406, 20243086402, 20243088583, 20243091029, 20243093421, 20243105382, 20243108444, 20243110703, 20243114513, 20243122314, 20243122316, 20243122985, 20243138757, 20243139017, 20243139060, 20243139065, 20243139067, 20243139068, 20243139436, 20243144131, 20243144492, 20243148034, 20243161574, 20243161576, 20243161577, 20243161618, 20243170149, 20243171376, 20243171377, 20243171378, 20243171603, 20243172011, 20243175765, 20243184493, 20243188296, 20243193260, 20243199389, 20243202407, 20243202446, 20243203759, 20243206451, 20243213357, 20243217947, 20243218733, 20243221780, 20243235946, 20243240386, 20243241413, 20243243733, 20243251218, 20248057291, 20253000165, 20253010141, 20253018084, 20253018584, 20253020833, 20253020835, 20253024276, 20253030839, 20253030842, 20253041412, 20253041857, 20253043524, 20253047426, 20253047427, 20253053284, 20253054285, 20253059657, 20253060008, 20253064635, 20253064700, 20253072090, 20253073898, 20253074504, 20253079092, 20253085706, 20253087843, 20253087844, 20253091144, 20253091437, 20253093502, 20253093503, 20253097652, 20253100027, 20253104598, 20253105786, 20253111767, 20253113174, 20253116687, 20253116688, 20253118064, 20253118238, 20253120156, 20253127445, 20253130936, 20253132160, 20253139982, 20253139984, 20253145020, 20253145222, 20253151596, 20253152475, 20253155992, 20253160667, 20253164925, 20253168048, 20258158560, 20213047248, 20213067446, 20213080289, 20213080429, 20213097638, 20213243354, 20223039846, 20223104060, 20223182664, 20223204693, 20223216618, 20233023188, 20233031376, 20233112645, 20233123024, 20233253571, 20243117826, 20243195827, 20243247601, 20253034468, 20253066858, 20203188256, 20206183641, 20213006179, 20213019001, 20213033007, 20213045509, 20213054267, 20213054285, 20213060906, 20213095959, 20213097766, 20213104687, 20213105902, 20213106368, 20213118350, 20213123179, 20213163092, 20213172640, 20213177044, 20213180531, 20213180972, 20213183068, 20213184041, 20213190740, 20213219326, 20213220823, 20213229989, 20213250859, 20213264649, 20214198893, 20216024907, 20223002525, 20223069235, 20223072415, 20223083065, 20223088937, 20223121922, 20223124518, 20223147592, 20223178413, 20223191468, 20223240260, 20223246895, 20226025099, 20233046442, 20233047128, 20233051005, 20233051134, 20233071131, 20233091628, 20233137674, 20233163804, 20233168634, 20233190035, 20233190237, 20233198742, 20233207573, 20233212972, 20233220333, 20233252617, 20234044893, 20242021679, 20243037511, 20243047331, 20243070628, 20243077744, 20243098472, 20243102203, 20243117950, 20243206451, 20243212839, 20243214674, 20243225124, 20243239599, 20243244704, 20243247822, 20243248186, 20246175568, 20248069235, 20252154695, 20253006613, 20253015104, 20253047229, 20253074245, 20253089497, 20253092368, 20253121908, 20253123782, 20253126284, 20253151024, 20203214052, 20213055295, 20213093133, 20213102878, 20213157275, 20213174788, 20213179622, 20213246557, 20213263427, 20214059446, 20214267413, 20223040983, 20223045794, 20223079963, 20223182930, 20223190526, 20223196709, 20223216294, 20223257114, 20223257539, 20233036950, 20233112796, 20233139855, 20233139924, 20233154366, 20233172618, 20233198527, 20233220357, 20233223971, 20233225853, 20233237550, 20233242174, 20243097622, 20243104505, 20243116510, 20243120223, 20243138835, 20243193270, 20243240356, 20243247822, 20252142913, 20253059813, 20253071439, 20253078232, 20253111671, 20253119045, 20253119860, 20253127797, 20253130534, 20213011508, 20213044831, 20213076892, 20213153186, 20213209808, 20213213067, 20223006715, 20223073400, 20223074715, 20223091841, 20223236281, 20223238691, 20233057698, 20233200290, 20233227568, 20233246638, 20243083869, 20243140180, 20243148615, 20243226934, 20243250036, 20258051287, 20223005258, 20223026315, 20223079568, 20243140054, 20243245802, 20248243505, 20253058957, 20253082041, 20203206677, 20203208269, 20203240163, 20213157085, 20213169929, 20213244452, 20223064471, 20233034632, 20233063856, 20233092916, 20233163804, 20233192613, 20233230599, 20234045558, 20243140833, 20243140837, 20243191797, 20253099376, 20253119860, 20253127790, 20253128683, 20253159171, 20213228253, 20233067235, 20233198480, 20243120930, 20243175923, 20258054115, 20213054221, 20213172821, 20223164538, 20233113661, 20233198086, 20243152288, 20243166591, 20243182842, 20253081159, 20204183452, 20213056801, 20213090861, 20213103653, 20213249489, 20223007619, 20233041050, 20233086681, 20233150047, 20233188366, 20233206558, 20233207841, 20233225389, 20242107524, 20243020743, 20243140837, 20243186647, 20243212143, 20243221872, 20243250650, 20253044434, 20253122038, 20253129393]

563

In [19]:
# now check the narrative file for these entries
fastfood_filtered_narratives = narratives[narratives['DocumentNumber'].isin(fastfood_document_numbers)]

In [20]:
fastfood_filtered_narratives

,DocumentNumber,County,Narrative
497,20203168201,Franklin County,Unit 1 was traveling south on Main Street pass...
570,20203169023,Franklin County,On 10-6-2020 Unit #1 was traveling from North ...
714,20203171089,Franklin County,On 10/9/2020 at approximately 8:55 PM; Officer...
986,20203175958,Franklin County,Diver of Unit 2 states she was in the drive th...
1513,20203183836,Franklin County,On 10/23/2020 at approxiamtely 4:53 PM; Office...
...,...,...,...
113951,20253164925,Franklin County,Driver of Unit #1 was driving through the park...
114296,20253168048,Franklin County,On 9/11/2025 the driver of Unit 2 stated he wa...
115281,20258051287,Franklin County,On March 19; 2025; at around 1613 hours; unit ...
115292,20258054115,Franklin County,Unit #1 was westbound on E. Broad Street when ...
115618,20258158560,Franklin County,Unit 1 and Unit 2 were both traveling westboun...

In [21]:
fastfood_filtered_narratives.loc[1513,"Narrative"]

# haha, in this exact entry, McDonald is the name of a person and has nothing to do with the location of a fastfood restaurant

'On 10/23/2020 at approxiamtely 4:53 PM; Officer A. McDonald #2811 and Officer S. Weeks #2832; wearing the uniform of the day and working CPD marked cruiser R-9160 as unit 122 were dispatched to I-70 W/B at S. Ohio Ave. in response to an auto accident. Upon arrival Officer McDonald spoke with the daughter of the driver of unit #2 Kalpana; who arrived at scene after the accident occured. Due to the language barrier Kalpana acted as a interpreter for officers and Guru Timsina; the operator of unit #1. According to Mr. Timsina he was struck in the rear of his vehicle by unit #1. Officer Weeks spoke to the driver of unit #1 who was identified by her Ohio drivers license as Mercedes Martell. Ms. Martell stated that unit #2 came to a abrupt stop and she crashed into the rear of unit #2. Both parties were issued a incident report number and advised to contact their insurance companies. '

In [22]:
fastfood_filtered_narratives.loc[115292,"Narrative"]

# here, "domino" is used in "domino effect" and not as the fastfood chain

'Unit #1 was westbound on E. Broad Street when he failed to come to a complete stop for the traffic ahead of him; causing him to crash into the rear of Unit #2 causing a domino effect with Unit #2 to crash into Unit #3 and Unit #3 to crash into Unit #4.'

In [23]:
# save the fastfood_filtered_narratives file as its own csv to go back to this
fastfood_filtered_narratives.to_csv("Data/Fastfood_filtered_narratives_DocumentNumber.csv", index=False)

As some accidents might not even be close to a fast food chain, we don't need to consider them at a later stage.

Now we want to match the locations of the accidents with the maps of the fast-food drive-throughs.